def JsonDebugError() -> str: return "debug.error";
def JsonHelpAppend()-> str: return "help.append";
def JsonHelpAvailable() -> str: return "help.available";
def JsonHelpHelp() -> str: return "help.help";
def JsonHelpList() -> str: return "help.list";
def JsonHelpLoad() -> str: return "help.load";
def JsonHelpMerge() -> str: return "help.merge";
def JsonHelpQuit() -> str: return "help.quit";
def JsonHelpSave() -> str: return "help.save";
def JsonHelpVersion() -> str: return "help.version";
def JsonHintEnjoy() -> str: return "hint.enjoy";
def JsonHintFullscreen() -> str: return "hint.fullscreen";
def JsonHintGreeting() -> str: return "hint.greeting";
def JsonInfoNoHistory() -> str: return "info.nohistory";
def JsonSuccessAppend() -> str: return "success.append";
def JsonSuccessLoad() -> str: return "success.load";
def JsonSuccessMerge() -> str: return "success.merge";
def JsonSuccessSave() -> str: return "success.save";
